package fr.formation.entity.backup2;
// Generated 4 mai 2022, 08:23:27 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", catalog = "test_brp")
public class Address implements java.io.Serializable {

	private int addressId;
	@Column(name = "address")
	private String address;
	@Column(name = "city")
	private String city;
	@Column(name = "zipCode")
	private String zipCode;
	@Column(name = "country")
	private String country;
//	private Set<Users> userses = new HashSet<Users>(0);

	public Address() {
	}

	public Address(int addressId, String address, String city, String zipCode, String country) {
		this.addressId = addressId;
		this.address = address;
		this.city = city;
		this.zipCode = zipCode;
		this.country = country;
	}

//	public Address(int addressId, String address, String city, String zipCode, String country, Set<Users> userses) {
//		this.addressId = addressId;
//		this.address = address;
//		this.city = city;
//		this.zipCode = zipCode;
//		this.country = country;
//		this.userses = userses;
//	}

	@Id

	@Column(name = "address_id", unique = true, nullable = false)
	public int getAddressId() {
		return this.addressId;
	}

	public void setAddressId(int addressId) {
		this.addressId = addressId;
	}

	@Column(name = "address", nullable = false, length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "city", nullable = false, length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "zip_code", nullable = false, length = 45)
	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	@Column(name = "country", nullable = false, length = 45)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "address")
//	public Set<Users> getUserses() {
//		return this.userses;
//	}
//
//	public void setUserses(Set<Users> userses) {
//		this.userses = userses;
//	}

}
