package fr.formation.entity.backup2;
// Generated 4 mai 2022, 08:23:27 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "book", catalog = "test_brp")
public class Book implements java.io.Serializable {

	private Integer bookId;
	private Users users;
	private String title;
	private String isbn;
	private String author;
	private String category;
	private int rentalRate;
	private float replacementCost;
	private Set<Inventory> inventories = new HashSet<Inventory>(0);
	private Set<Forum> forums = new HashSet<Forum>(0);

	public Book() {
	}

	public Book(Users users, String title, String isbn, String author, String category, int rentalRate,
			float replacementCost) {
		this.users = users;
		this.title = title;
		this.isbn = isbn;
		this.author = author;
		this.category = category;
		this.rentalRate = rentalRate;
		this.replacementCost = replacementCost;
	}

	public Book(Users users, String title, String isbn, String author, String category, int rentalRate,
			float replacementCost, Set<Inventory> inventories, Set<Forum> forums) {
		this.users = users;
		this.title = title;
		this.isbn = isbn;
		this.author = author;
		this.category = category;
		this.rentalRate = rentalRate;
		this.replacementCost = replacementCost;
		this.inventories = inventories;
		this.forums = forums;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "book_id", unique = true, nullable = false)
	public Integer getBookId() {
		return this.bookId;
	}

	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "title", nullable = false, length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "ISBN", nullable = false, length = 45)
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@Column(name = "author", nullable = false, length = 45)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "category", nullable = false, length = 45)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "rental-rate", nullable = false)
	public int getRentalRate() {
		return this.rentalRate;
	}

	public void setRentalRate(int rentalRate) {
		this.rentalRate = rentalRate;
	}

	@Column(name = "replacement_cost", nullable = false, precision = 12, scale = 0)
	public float getReplacementCost() {
		return this.replacementCost;
	}

	public void setReplacementCost(float replacementCost) {
		this.replacementCost = replacementCost;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "book")
	public Set<Inventory> getInventories() {
		return this.inventories;
	}

	public void setInventories(Set<Inventory> inventories) {
		this.inventories = inventories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "book")
	public Set<Forum> getForums() {
		return this.forums;
	}

	public void setForums(Set<Forum> forums) {
		this.forums = forums;
	}

}
