package fr.formation.entity.backup2;
// Generated 4 mai 2022, 08:23:27 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Delivery generated by hbm2java
 */
@Entity
@Table(name = "delivery", catalog = "test_brp")
public class Delivery implements java.io.Serializable {

	private Integer deliveryId;
	private Rental rental;
	private String deliveryMethod;

	public Delivery() {
	}

	public Delivery(Rental rental, String deliveryMethod) {
		this.rental = rental;
		this.deliveryMethod = deliveryMethod;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "delivery_id", unique = true, nullable = false)
	public Integer getDeliveryId() {
		return this.deliveryId;
	}

	public void setDeliveryId(Integer deliveryId) {
		this.deliveryId = deliveryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rental_id", nullable = false)
	public Rental getRental() {
		return this.rental;
	}

	public void setRental(Rental rental) {
		this.rental = rental;
	}

	@Column(name = "delivery_method", nullable = false, length = 45)
	public String getDeliveryMethod() {
		return this.deliveryMethod;
	}

	public void setDeliveryMethod(String deliveryMethod) {
		this.deliveryMethod = deliveryMethod;
	}

}
