package fr.formation.entity.backup2;
// Generated 4 mai 2022, 08:23:27 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Photo generated by hbm2java
 */
@Entity
@Table(name = "photo", catalog = "test_brp")
public class Photo implements java.io.Serializable {

	private Integer photoId;
	private Users users;
	private byte[] photo;
	private String photoRole;

	public Photo() {
	}

	public Photo(Users users, byte[] photo, String photoRole) {
		this.users = users;
		this.photo = photo;
		this.photoRole = photoRole;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "photo_id", unique = true, nullable = false)
	public Integer getPhotoId() {
		return this.photoId;
	}

	public void setPhotoId(Integer photoId) {
		this.photoId = photoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "photo", nullable = false)
	public byte[] getPhoto() {
		return this.photo;
	}

	public void setPhoto(byte[] photo) {
		this.photo = photo;
	}

	@Column(name = "photo_role", nullable = false, length = 45)
	public String getPhotoRole() {
		return this.photoRole;
	}

	public void setPhotoRole(String photoRole) {
		this.photoRole = photoRole;
	}

}
