package fr.formation.entity.backup2;
// Generated 4 mai 2022, 08:23:27 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rental generated by hbm2java
 */
@Entity
@Table(name = "rental", catalog = "test_brp")
public class Rental implements java.io.Serializable {

	private Integer rentalId;
	private Inventory inventory;
	private Users users;
	private Date rentalDate;
	private Date returnDate;
	private Set<Delivery> deliveries = new HashSet<Delivery>(0);
	private Set<Payment> payments = new HashSet<Payment>(0);

	public Rental() {
	}

	public Rental(Inventory inventory, Users users, Date rentalDate) {
		this.inventory = inventory;
		this.users = users;
		this.rentalDate = rentalDate;
	}

	public Rental(Inventory inventory, Users users, Date rentalDate, Date returnDate, Set<Delivery> deliveries,
			Set<Payment> payments) {
		this.inventory = inventory;
		this.users = users;
		this.rentalDate = rentalDate;
		this.returnDate = returnDate;
		this.deliveries = deliveries;
		this.payments = payments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "rental_id", unique = true, nullable = false)
	public Integer getRentalId() {
		return this.rentalId;
	}

	public void setRentalId(Integer rentalId) {
		this.rentalId = rentalId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "inventory_id", nullable = false)
	public Inventory getInventory() {
		return this.inventory;
	}

	public void setInventory(Inventory inventory) {
		this.inventory = inventory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "rental_date", nullable = false, length = 10)
	public Date getRentalDate() {
		return this.rentalDate;
	}

	public void setRentalDate(Date rentalDate) {
		this.rentalDate = rentalDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "return_date", length = 10)
	public Date getReturnDate() {
		return this.returnDate;
	}

	public void setReturnDate(Date returnDate) {
		this.returnDate = returnDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rental")
	public Set<Delivery> getDeliveries() {
		return this.deliveries;
	}

	public void setDeliveries(Set<Delivery> deliveries) {
		this.deliveries = deliveries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rental")
	public Set<Payment> getPayments() {
		return this.payments;
	}

	public void setPayments(Set<Payment> payments) {
		this.payments = payments;
	}

}
