package fr.formation.inti.entity;
// Generated 4 mai 2022, 10:40:33 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", catalog = "test_brp")
public class Address implements java.io.Serializable {

	private Integer addressId;
	@Column(name = "address")
	private String address;
	@Column(name = "zipCode")
	private String city;
	@Column(name = "city")
	private String zipCode;
	@Column(name = "country")
	private String country;

	public Address() {
	}

	public Address(int addressId, String address, String city, String zipCode, String country) {
		this.addressId = addressId;
		this.address = address;
		this.city = city;
		this.zipCode = zipCode;
		this.country = country;
	}
	
	public Address(String address, String city, String zipCode, String country) {
		this.address = address;
		this.city = city;
		this.zipCode = zipCode;
		this.country = country;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "address_id", unique = true, nullable = false)
	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(int addressId) {
		this.addressId = addressId;
	}

	@Column(name = "address", nullable = false, length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "city", nullable = false, length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "zip_code", nullable = false, length = 45)
	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	@Column(name = "country", nullable = false, length = 45)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}


}
