package fr.formation.entity.backup;
// Generated 3 mai 2022, 09:10:20 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", catalog = "brp_test")
public class Address implements java.io.Serializable {

	private int addressId;
	@Column(name = "address")
	private String address;
	@Column(name = "zipCode")
	private String zipCode;
	@Column(name = "city")
	private String city;
	@Column(name = "country")
	private String country;
	

	public Address() {
	}

	public Address(int addressId, String address, String zipCode, String city, String country) {
		this.addressId = addressId;
		this.address = address;
		this.zipCode = zipCode;
		this.city = city;
		this.country = country;
	}

	

	@Id

	@Column(name = "address_id", unique = true, nullable = false)
	public int getAddressId() {
		return this.addressId;
	}

	public void setAddressId(int addressId) {
		this.addressId = addressId;
	}

	@Column(name = "address", nullable = false, length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "zip_code", nullable = false, length = 45)
	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	@Column(name = "city", nullable = false, length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "country", nullable = false, length = 45)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	

}
